/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package utspemvis3c;



/**
 *
 * @author engko
 */
public class Games extends javax.swing.JFrame {

    /**
     * Creates new form Games
     */
    String Gunting, Batu, Kertas;
    public Games() {
        initComponents();
        Gunting = "Gunting";
        Kertas = "Kertas";
        Batu = "Batu";
    }
    
    private void GuntingTekan(){
        UserField.setText(Gunting);     
    }
    
    private void KertasTekan(){
        UserField.setText(Kertas);
    }
    
    private void BatuTekan(){
        UserField.setText(Batu);
    }
    
    private void Acak(){
        int BilAcak;
        BilAcak = (int) (Math.random()*3);
        if (BilAcak == 0){
            KomField.setText(Gunting);
        }else if (BilAcak ==1){
            KomField.setText(Kertas);
        }if (BilAcak ==2){
            KomField.setText(Batu);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        GuntingTekan = new javax.swing.JButton();
        KertasTekan = new javax.swing.JButton();
        batuTekan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        KomField = new javax.swing.JTextField();
        UserField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("GAMES MINI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 544, 130));

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setLayout(new java.awt.GridLayout());

        GuntingTekan.setIcon(new javax.swing.ImageIcon("C:\\Users\\engko\\Pictures\\gamess\\1.png")); // NOI18N
        jPanel2.add(GuntingTekan);

        KertasTekan.setIcon(new javax.swing.ImageIcon("C:\\Users\\engko\\Pictures\\gamess\\2.png")); // NOI18N
        KertasTekan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KertasTekanActionPerformed(evt);
            }
        });
        jPanel2.add(KertasTekan);

        batuTekan.setIcon(new javax.swing.ImageIcon("C:\\Users\\engko\\Pictures\\gamess\\3.png")); // NOI18N
        jPanel2.add(batuTekan);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 130, 560, 120));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KomFieldActionPerformed(evt);
            }
        });
        jPanel3.add(KomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 260, 150));

        UserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });
        jPanel3.add(UserField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 260, 150));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("PILIHAN HARRY GANTENG");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("PILIHAN KOMPUTER");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 550, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KertasTekanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KertasTekanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KertasTekanActionPerformed

    private void KomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KomFieldActionPerformed

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFieldActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Games().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuntingTekan;
    private javax.swing.JButton KertasTekan;
    private javax.swing.JTextField KomField;
    private javax.swing.JTextField UserField;
    private javax.swing.JButton batuTekan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
